email: tilt@improfestival.ee
baseurl: ""
url: "https://improfestival.ee"
languages: ["et", "en"]
timezone: "Europe/Tallinn"
exclude:
  - Gemfile
  - .bundle
  - .sass-cache
  - nginx.conf
  - docker-compose.yml
  - .asset-cache
  - Gemfile.lock
  - Dockerfile
  - README.md
  - .travis.yml
  - vendor
  - package-lock.json
  - bower.json
  - node_modules
  - bower.json"
environment: production

markdown: kramdown
sass:
  sass_dir: _assets/css
plugins: 
 - jekyll-assets
 - jekyll-multiple-languages-plugin
 - jekyll-coffeescript

defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: team
  - scope:
      path: ""
      type: workshops
    values:
      layout: workshop
      show_in_schedule: true
  - scope:
      path: ""
      type: performances
    values:
      layout: performance
      show_in_schedule: true

collections:
  workshops:
    output: true
  team:
    output: true
  performances:
    output: true

assets:
  autoprefixer:
    browsers: ["last 4 versions","> 5%"]
  cache_type: memory
  digest: true
  plugins:
    img: { optim: {}}
  sources:  
    - "_assets/bower/font-awesome/fonts"
    - "_assets/bower/open-sans-fontface/fonts"
    - "_assets/bower/bootstrap-sass/assets/javascripts"
    - "_assets/bower/jquery/dist"
    - "_assets/bower"
    - "_assets/img"
    - "_assets/fonts"
  features:
   automatic_img_size: false

extlinks:
  attributes:
    target: _blank
  rel_exclude:
    - 2013.improfestival.ee
    - 2014.improfestival.ee
    - 2015.improfestival.ee
    - 2016.improfestival.ee
    - 2017.improfestival.ee

social:
  twitter: TILT_Improfest
  facebook: https://www.facebook.com/tilt.improfestival
  ical: /schedule.ics
  instagram: https://www.instagram.com/tilt.improfestival
  youtube: https://www.youtube.com/c/TILT-InternationalImprovFestival

compress_html:
  clippings: all
  ignore:
    envs:
      - development
